# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 953fbbdc68c29ef9f05c016b583ee384a8a8fee1e3ae66891f0628a63c3d70f291d1e6dedb27b63d19dd4f01a34a9f1efa19b91e8a1be84ec72c623c4ebba418

test:
  secret_key_base: b10390cf0e4ead888262cf6d998fdba779977a503ae4b738895207477a6c02a8fd042a3ffc03a15f449f4ea0094d9e683d01ec922ff164d21e63e02a07eaad48

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
